name: windows_widgets
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  #defualt
  cupertino_icons: ^1.0.8
  #windows
  window_manager: ^0.4.3
  screen_retriever: ^0.2.0
  flutter_acrylic: ^1.1.2
  #windows api
  win32: ^5.10.1
  ffi: ^2.1.3
  #database
  hive_ce: ^2.10.1
  hive_ce_flutter: ^2.2.0
  #state management
  flutter_bloc: ^7.0.0
  #utils
  file_picker: ^9.0.1
  #UI enhance
  animated_reorderable_list: ^1.1.5
  lottie: ^3.3.1
  # super_context_menu: ^0.8.24
  dropdown_button2: ^2.3.9
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/animations/
    - assets/images/

  fonts:
    - family: Nova
      fonts:
        - asset: assets/fonts/Nova-Regular.ttf
    - family: Abel
      fonts:       
        - asset: assets/fonts/Abel-Regular.ttf
    - family: Custom
      fonts:       
        - asset: assets/fonts/Custom.ttf