name: windows_widgets
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  window_manager: ^0.4.3
  screen_retriever: ^0.2.0
  flutter_acrylic: ^1.1.4
  file_picker: ^9.0.1
  win32: ^5.10.1
  ffi: ^2.1.3
  sqflite: ^2.3.0
  path:
  sqflite_common_ffi: ^2.3.4+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
  #   - images/a_dot_ham.jpeg


  fonts:
    - family: Nova
      fonts:
        - asset: assets/fonts/Nova-Regular.ttf
    - family: Abel
      fonts:       
        - asset: assets/fonts/Abel-Regular.ttf
    - family: Custom
      fonts:       
        - asset: assets/fonts/Custom.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

